### ISSUE TITLE
impossible to get `Nfreq_min`

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#100]
66 errors (out of 432 tiff processed) with this new error using latest release #2023.03.28

```python
Traceback (most recent call last):
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/bin/L1B_xspectra_IW_SLC_IFR", line 8, in <module>
    sys.exit(main())
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/lib/python3.9/site-packages/xsarslc/scripts/L1B_xspectra_IW_SLC_IFR.py", line 169, in main
    generate_IW_L1Bxspec_product(slc_iw_path=slc_iw_path, output_filename=output_filename,
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/lib/python3.9/site-packages/xsarslc/scripts/L1B_xspectra_IW_SLC_IFR.py", line 92, in generate_IW_L1Bxspec_product
    one_subswath_xspectrum_dt = proc.compute_subswath_xspectra(dt, polarization=polarization.upper(),
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/lib/python3.9/site-packages/xsarslc/processing/xspectra.py", line 38, in compute_subswath_xspectra
    intra_xs = compute_IW_subswath_intraburst_xspectra(dt, polarization=polarization, tile_width=tile_width_intra,
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/lib/python3.9/site-packages/xsarslc/processing/xspectra.py", line 168, in compute_IW_subswath_intraburst_xspectra
    burst_xspectra = tile_burst_to_xspectra(burst, dt['geolocation_annotation'], dt['orbit'], dt['calibration'],
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/lib/python3.9/site-packages/xsarslc/processing/intraburst.py", line 224, in tile_burst_to_xspectra
    Nfreq_min = min([x.sizes['freq_sample'] if 'freq_sample' in x.dims else np.nan for x in xs if 'freq_sample' in x.dims])
ValueError: min() arg is an empty sequence
INFO:prun:[2023-03-28T07:51:37Z] End of processing for input line 1 : '/home/datawork-cersat-public/project/mpc-sentinel1/data/esa/sentinel-1a/L1/IW/S1A_IW_SLC__1S/2021/065/S1A_IW_SLC__1SDV_20210306T072852_20210306T072919_036874_04562A_716A.SAFE/measurement/s1a-iw1-slc-vh-20210306t072854-20210306t072919-036874-04562a-001.tiff tiles18km 1.4d'. EXIT_CODE=1

```

**Comment by lanougue** [comment]
solved in #103
