### ISSUE TITLE
issue with management of empty inter burst cross spectra

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#43]
```python
Traceback (most recent call last):
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/scripts/L1B_xspectra_IW_SLC_IFR.py", line 138, in <module>
    generate_IW_L1Bxspec_product(slc_iw_path=slc_iw_path,output_filename=output_filename, dev=args.dev,
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/scripts/L1B_xspectra_IW_SLC_IFR.py", line 75, in generate_IW_L1Bxspec_product
    one_subswath_xspectrum_dt = proc.compute_subswath_xspectra(dt,pol=polarization.upper(),
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/xspectra.py", line 29, in compute_subswath_xspectra
    intra_xs = compute_IW_subswath_intraburst_xspectra(dt, **kwargs)
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/xspectra.py", line 155, in compute_IW_subswath_intraburst_xspectra
    dims_to_transpose = [d for d in ['burst', 'tile_sample','tile_line', 'freq_sample','freq_line'] if d in xspectra.dims] # for homogeneous order of dimensions with interburst
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/xspectra.py", line 155, in <listcomp>
    dims_to_transpose = [d for d in ['burst', 'tile_sample','tile_line', 'freq_sample','freq_line'] if d in xspectra.dims] # for homogeneous order of dimensions with interburst
AttributeError: 'list' object has no attribute 'dims'
```

**Comment by lanougue** [comment]
solved in #42
