### ISSUE TITLE
`get_centroid` could crash for case with weird signal

### ISSUE THREAD

**Issue by agrouaze** [umr-lops/xsar_slc#78]
```python
Traceback (most recent call last):
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/scripts/L1B_xspectra_WV_SLC_IFR.py", line 158, in <module>
    generate_WV_L1Bxspec_product(slc_wv_path=slc_wv_path,output_filename=output_filename,
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/scripts/L1B_xspectra_WV_SLC_IFR.py", line 66, in generate_WV_L1Bxspec_product
    xs0 = proc.compute_WV_intraburst_xspectra(dt=dt,
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/xspectra.py", line 110, in compute_WV_intraburst_xspectra
    xspectra = tile_burst_to_xspectra(burst, dt['geolocation_annotation'], dt['orbit'], dt['calibration'],
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/intraburst.py", line 183, in tile_burst_to_xspectra
    xspecs = compute_intraburst_xspectrum(mod, mean_incidence, slant_spacing, azimuth_spacing,
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/intraburst.py", line 287, in compute_intraburst_xspectrum
    xspecs = compute_looks(image, azimuth_dim=azimuth_dim, synthetic_duration=synthetic_duration,**kwargs) 
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/intraburst.py", line 364, in compute_looks
    centroid = get_centroid(mydop, dim=freq_azi_dim, method='maxfit')
  File "/home1/datahome/agrouaze/sources/git/xsar_slc/xsarslc/processing/xspectra.py", line 421, in get_centroid
    p, r = curve_fit(fit_gauss, fit_spectrum[dim], fit_spectrum.data, p0=[a_estimate, c_estimate, l_estimate])
  File "/home/datawork-cersat-public/cache/project/mpc-sentinel1/workspace/mamba/envs/xsar_oct22/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py", line 839, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 800.
INFO:prun:[2023-03-15T15:00:02Z] End of processing for input line 1 : '/home/datawork-cersat-public/project/mpc-sentinel1/data/esa/sentinel-1b/L1/WV/S1B_WV_SLC__1S/2021/356/S1B_WV_SLC__1SSV_20211222T173736_20211222T180050_030141_039963_C651.SAFE/measurement/s1b-wv1-slc-vv-20211222t175441-20211222t175444-030141-039963-071.tiff tiles20km 1.4a'. EXIT_CODE=1
```

**Comment by lanougue** [comment]
should be fixed with #83
